<?php
        var_dump($tirageLoterie);
    ?>

<!DOCTYPE html>
<html>
<head>
    <title>Loterie PHP</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="main.css">
    
</head>
<body>

<header>
   
</header>

<main>
    
    <p>Tirage du loto</p>
    <table>
        <tr>
            <?= $tirageLoterie[0]; ?>
            <td><?php echo $tirageLoterie[0]; ?></td>
            <td><?php echo $tirageLoterie[1]; ?></td>
            <td><?php echo $tirageLoterie[2]; ?></td>
            <td><?php echo $tirageLoterie[3]; ?></td>
            <td><?php echo $tirageLoterie[4]; ?></td>
            <td><?php echo $tirageLoterie[5]; ?></td>
        </tr>
        
     </table>


</main>
	


<footer></footer>




</body>

</html>